### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by PQuod** [PQuod/dev_portfolio#1]
- [ ] Add an RSS feed to the log
- [ ] Add mobile and tablet versions
- [ ] Add a dark theme ?
